version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API MinIO (S3 compatible)
      - "9001:9001"   # Console web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  flight-server:
    build: ./flight_server
    container_name: flight-server
    ports:
      - "8815:8815"   # Port gRPC pour Arrow Flight
    volumes:
      - ./flight_server:/app
      - ./ingestion/data:/data
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      S3_ENDPOINT: http://minio:9000
    depends_on:
      - minio

volumes:
  minio_data:
