dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ingestion/data/duckhouse.duckdb
      threads: 4
    prod:
      type: trino
      schema: analytics
      database: iceberg
      host: localhost
      port: 8080
      user: datahut
      password: ''
      http_scheme: http
      threads: 10
